spring:
  jpa:
    defer-datasource-initialization:true
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    initialization-mode: always
    url: r2dbc:h2:mem:///replace_key?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
server:
  port: 8080
  shutdown: graceful

